/* ============================================================
   RUTA VERDE — DATOS
   Fotos: Wikimedia Commons (autor y licencia en cada entrada).
   Restaurantes y hospedajes: negocios reales del Quindío.
   Aquí no hay precios: solo recomendaciones. Verifica horarios
   y disponibilidad antes de viajar.
   ============================================================ */

/* ---------- FOTOS REALES (Wikimedia Commons) ---------- */
const PHOTOS = {
  heroCocora:{f:'Valle del Cocora junio 2025 08.jpg', t:'Valle del Cocora', by:'AmiGueko', lic:'CC BY-SA 4.0'},
  cocora:{f:'Palmas de cera, Valle del cócora.jpg', t:'Palmas de cera del Valle del Cocora', by:'Tefalifenature', lic:'CC BY-SA 4.0'},
  cocora2:{f:'Valle de Cocora. Salento, Quindío.jpg', t:'Valle de Cocora', by:"It's JuanFe", lic:'CC BY-SA 4.0'},
  cocora3:{f:'Valle de Cocora 5.JPG', t:'Valle de Cocora', by:'Sergiodbotero', lic:'CC BY-SA 4.0'},
  cocora4:{f:'Valle del Cocora junio 2025 13.jpg', t:'Valle del Cocora', by:'AmiGueko', lic:'CC BY-SA 4.0'},
  cocora5:{f:'Valle del Cocora junio 2025 21.jpg', t:'Valle del Cocora', by:'AmiGueko', lic:'CC BY-SA 4.0'},
  cocora6:{f:'Valle de Cocora 14.JPG', t:'Valle de Cocora', by:'Sergiodbotero', lic:'CC BY-SA 4.0'},
  cocora7:{f:'Valle del Cócora, Quindio - Colombia.jpg', t:'Valle del Cocora', by:'Adrianvargasag', lic:'CC BY-SA 4.0'},
  palma:{f:'Palma de Cera del Quindío.jpg', t:'Palma de cera del Quindío', by:'CamiloBer04', lic:'CC BY-SA 4.0'},
  palmsSign:{f:'Forest of Palms Sign.jpg', t:'Bosque de palmas, Cocora', by:'Milentezoom', lic:'CC BY-SA 4.0'},
  salento:{f:'View of Salento, Colombia 01.jpg', t:'Salento', by:'Bernard Gagnon', lic:'CC BY-SA 4.0'},
  salento2:{f:'Plaza Principal Salento - panoramio.jpg', t:'Plaza principal de Salento', by:'rothware', lic:'CC BY-SA 3.0'},
  salento3:{f:'Plaza Principal de Salento - Iglesia al fondo - panoramio.jpg', t:'Plaza de Salento', by:'rothware', lic:'CC BY-SA 3.0'},
  salento4:{f:'Iglesia de Salento - Plaza Principal - panoramio (1).jpg', t:'Iglesia de Salento', by:'rothware', lic:'CC BY-SA 3.0'},
  salento5:{f:'Rio en la carretera de entrada a Salento - panoramio (2).jpg', t:'Río en la entrada a Salento', by:'rothware', lic:'CC BY-SA 3.0'},
  filandia:{f:'Calle 7, Filandia 01.jpg', t:'Calle 7 de Filandia', by:'Bernard Gagnon', lic:'CC BY-SA 4.0'},
  filandia2:{f:'Vista de alrededores de Filandia, Quindío (14205522090).jpg', t:'Alrededores de Filandia', by:'Alejandro Bayer Tamayo', lic:'CC BY-SA 2.0'},
  filandia3:{f:'Calle del Convento, Filandia.jpg', t:'Calle del Convento, Filandia', by:'Bernard Gagnon', lic:'CC BY-SA 4.0'},
  filandia4:{f:'Calle de la Cruz, Filandia.jpg', t:'Calle de la Cruz, Filandia', by:'Bernard Gagnon', lic:'CC BY-SA 4.0'},
  filandia5:{f:'Calle 7, Filandia 02.jpg', t:'Calles de Filandia', by:'Bernard Gagnon', lic:'CC BY-SA 4.0'},
  filandia6:{f:'Filandiaquindio.JPG', t:'Filandia', by:'Darthvader2', lic:'CC BY-SA 4.0'},
  filandia7:{f:'FilandiaQuindioSendero.jpg', t:'Sendero en Filandia', by:'Hdhdhdybooty', lic:'CC BY-SA 4.0'},
  filandia8:{f:'Crafts Colombia, Filandia.jpg', t:'Cestería de Filandia', by:'Bernard Gagnon', lic:'CC BY-SA 4.0'},
  filandia9:{f:'Filandia (Quindío, Colombia).jpg', t:'Filandia', by:'Museo de América', lic:'CC BY-SA 4.0'},
  circasia:{f:'Circasia Ago 2017 (30).jpg', t:'Circasia', by:'Darthvader2', lic:'CC BY-SA 4.0'},
  bahareque:{f:'Casa Colonial en Bahareque, Manzana 095, El Cerrito, Valle, Colombia 01.jpg', t:'Casa en bahareque', by:'Diego Carrejo Murillo', lic:'CC BY-SA 3.0'},
  armenia:{f:'Armenia, Quindio, Colombia - panoramio - Jimmy Gómez N (5).jpg', t:'Armenia', by:'Jimmy Gómez N', lic:'CC BY-SA 3.0'},
  museo:{f:'Museo del Oro Quimbaya.jpg', t:'Museo del Oro Quimbaya', by:'CamiloBer04', lic:'CC BY-SA 4.0'},
  quindio:{f:'Quindío.jpg', t:'Paisaje del Quindío', by:'CamiloB4', lic:'CC BY-SA 4.0'},
  parque:{f:'Colombian National Coffee Park 195.JPG', t:'Parque del Café', by:'Uria Ashkenazy', lic:'CC BY-SA 2.5'},
  parque2:{f:'Parque del Café Quindio Colombia.jpg', t:'Parque del Café', by:'Freed5.musicfly', lic:'CC BY-SA 4.0'},
  parque3:{f:'Parque del café 2.JPG', t:'Parque del Café', by:'Sergiodbotero', lic:'CC BY-SA 4.0'},
  casaTipica:{f:'Casa típica Quindio, parque del cafe.jpg', t:'Casa típica quindiana', by:'Franciscokarriere', lic:'CC BY-SA 4.0'},
  montenegro:{f:'Parroquia San José de Montenegro.jpg', t:'Parroquia de Montenegro', by:'CamiloB4', lic:'CC BY-SA 4.0'},
  quimbaya:{f:'QUIMBAYA.jpg', t:'Quimbaya', by:'CamiloB4', lic:'CC BY-SA 4.0'},
  buenavista:{f:'Parroquia Nuestra Señora del Carmen de Buenavista.jpg', t:'Parroquia de Buenavista', by:'CamiloB4', lic:'CC BY-SA 4.0'},
  buenavista2:{f:'Buena vista - Quindío - Flickr - Alejandro Bayer.jpg', t:'Buenavista', by:'Alejandro Bayer Tamayo', lic:'CC BY-SA 2.0'},
  genova:{f:'Génova Quindío.jpg', t:'Montañas del Quindío', by:'Infogenova', lic:'CC BY-SA 4.0'},
  calarca:{f:'Inglesia San José de Calarcá.jpg', t:'Iglesia de Calarcá', by:'CamiloBer04', lic:'CC BY-SA 4.0'},
  cafetal:{f:'Chinchiná cafetal.jpg', t:'Cafetal', by:'Ricohin', lic:'CC BY 3.0'},
  cafetal2:{f:'Cafetal (14813193969).jpg', t:'Cafetal del Eje Cafetero', by:'Alejandro Bayer Tamayo', lic:'CC BY-SA 2.0'},
  trucha:{f:'Fried trout Trucha frita con papas y arroz (31008005061).jpg', t:'Trucha frita', by:'Lucerito Corrales', lic:'CC BY 2.0'},
  bandeja:{f:'Bandepaisabog.JPG', t:'Bandeja paisa', by:'Jdvillalobos', lic:'CC BY-SA 4.0'},
  sancocho:{f:'Sancocho-hueso.JPG', t:'Sancocho', by:'Jdvillalobos', lic:'CC BY-SA 4.0'},
  calentado:{f:'Calentao.jpg', t:'Calentado', by:'Juancplanb', lic:'CC BY-SA 4.0'},
  cafeLeche:{f:'Cafeconleche.jpg', t:'Café con leche', by:'Jeremy Keith', lic:'CC BY 2.0'},
  cafeGranos:{f:'Roasted coffee beans.jpg', t:'Café tostado', by:'MarkSweep', lic:'Dominio público'},
  arepa:{f:'Arepitas Food Macro.jpg', t:'Arepas', by:'Steven Depolo', lic:'CC BY 2.0'},
  chorizo:{f:'Chorizos P6021974.jpg', t:'Chorizos a la parrilla', by:'Amasuela-Luis Lafuente Agudín', lic:'CC BY-SA 4.0'},
  comida1:{f:'Comida colombiana.jpg', t:'Comida colombiana', by:'Galahad', lic:'CC BY-SA 4.0'},
  comida2:{f:'Comida colombiana 2.jpg', t:'Comida colombiana', by:'Galahad', lic:'CC BY-SA 4.0'},
  almuerzo1:{f:'Almuerzo - antes.jpg', t:'Almuerzo', by:'Oskari Kettunen', lic:'CC BY 2.0'},
  almuerzo2:{f:'Lunch - Almuerzo (23-10-2021) (Colombia).jpg', t:'Almuerzo colombiano', by:'JSeb05', lic:'CC BY-SA 4.0'},
  almuerzo3:{f:'Almuerzo 2 (Septiembre 21-2022).jpg', t:'Almuerzo colombiano', by:'JSeb05', lic:'CC BY-SA 4.0'},
  chuleta:{f:'Chuleta Valluna - Colombiana.jpg', t:'Chuleta colombiana', by:'Makike.cortes', lic:'CC BY-SA 3.0'},
  ajiaco:{f:'Ajiaco bogotano.jpg', t:'Ajiaco', by:'Armando Ávila Carreto', lic:'CC BY-SA 4.0'},
  aborrajado:{f:'Aborrajados de plátano maduro.jpg', t:'Aborrajados de plátano', by:'Ethnobotanical Historian', lic:'CC BY-SA 4.0'},
  empanada:{f:'Empanada, flaky pastry perfection.jpg', t:'Empanadas', by:'JeanneKikoy', lic:'CC BY-SA 4.0'},
  croquetas:{f:'Croquetas de carne oreada.jpg', t:'Croquetas de carne oreada', by:'Fabiantrd', lic:'CC BY-SA 4.0'},
  hamburguesa:{f:'Hamburger and cooking table, Manizales, Colombia (Unsplash).jpg', t:'Hamburguesa artesanal', by:'Pablo Merchán Montes', lic:'CC0'},
  aguapanela:{f:'Aguapanela-Colombiana-3-2.jpg', t:'Aguapanela con queso', by:'Mappa Stellae', lic:'CC BY-SA 4.0'}
};

/* ---------- PUEBLOS ---------- */
const TOWNS = {
  armenia:{name:'Armenia', tag:'la Ciudad Milagro', zones:['armenia'], ph:'armenia',
    intro:'Capital del Quindío y punto de llegada: aquí está el aeropuerto y el terminal desde donde salen los buses a todos los pueblos. Buena base si quieres dormir en ciudad y salir cada día a un municipio distinto.',
    acts:[['Museo del Oro Quimbaya','Colección de orfebrería quimbaya en un edificio premiado. Revisa horarios: cierra algunos días.'],
      ['Parque de la Vida','Senderos, lagos y guaduales en plena ciudad. Ideal para caminar en la tarde.'],
      ['Plaza de Bolívar','El corazón de la ciudad, con el Monumento al Esfuerzo.'],
      ['Parque Sucre','Zona tradicional rodeada de cafeterías y comida típica.'],
      ['Terminal de Transportes','Desde aquí salen los buses a Salento, Filandia, Circasia, Quimbaya, Montenegro y Buenavista.']],
    how:'Es el punto de partida. Tiene aeropuerto (El Edén) y terminal de buses. Dentro de la ciudad muévete en taxi, app o bus urbano.'},
  circasia:{name:'Circasia', tag:'el pueblo del Cementerio Libre', zones:['circasia'], ph:'circasia',
    intro:'Pueblo cafetero tranquilo a media hora de Armenia, de camino a Filandia. Perfecto para una parada corta: un café, el parque y el Cementerio Libre.',
    acts:[['Cementerio Libre','Cementerio laico fundado por librepensadores, abierto a personas de todas las creencias. Es el sitio más conocido del pueblo.'],
      ['Parque principal e iglesia','Ambiente de pueblo real, sin multitudes, con cafeterías alrededor.'],
      ['Fincas cafeteras cercanas','Varias fincas de la zona reciben visitantes para tour de café y almuerzo campesino.'],
      ['Ruta a Filandia','Circasia queda en el camino: combina los dos pueblos el mismo día.']],
    how:'Buses y busetas frecuentes desde el Terminal de Armenia, unos 30 minutos.'},
  filandia:{name:'Filandia', tag:'el mirador de los atardeceres', zones:['filandia'], ph:'filandia2',
    intro:'Pueblo de calles coloridas, cestería y cafés de especialidad. Menos lleno que Salento y con uno de los mejores atardeceres del Quindío desde su mirador.',
    acts:[['Mirador Colina Iluminada','Torre de madera con vista de 360 grados: en día claro se ven varios departamentos. Ve al atardecer.'],
      ['Calles del centro','Casas de balcones pintados y puertas talladas alrededor de la plaza. Es el pueblo más fotogénico de la zona.'],
      ['Talleres de cestería','Filandia es famosa por sus canastos: varios talleres muestran el proceso.'],
      ['Cafés de especialidad','Buena escena de café de origen para probar métodos filtrados.'],
      ['Miradores naturales','Senderos cortos en los alrededores con vista al valle del río Cauca.']],
    how:'Buses desde el Terminal de Armenia, entre 45 minutos y una hora. También hay transporte directo desde Salento.'},
  salento:{name:'Salento', tag:'balcones de mil colores', zones:['salento','cocora'], ph:'salento2',
    intro:'El pueblo más visitado del Quindío y la puerta al Valle del Cocora. Calle Real llena de artesanías, trucha en todos los restaurantes y Willys saliendo de la plaza.',
    acts:[['Valle del Cocora','El bosque de palmas de cera, árbol nacional. Se llega en Willys desde la plaza, unos 30 minutos.'],
      ['Calle Real','La calle de artesanías y cafés que sube desde la plaza hasta las escaleras del mirador.'],
      ['Mirador de Salento','Al final de la Calle Real, subiendo unas escalinatas: vista al valle de Cocora y las montañas.'],
      ['Tour de café en finca','Varias fincas alrededor del pueblo enseñan el proceso del grano y terminan con una taza.'],
      ['Tejo','El deporte nacional con pólvora: hay canchas en el pueblo para probarlo.']],
    how:'Buses desde el Terminal de Armenia cada pocos minutos, alrededor de una hora. Para el Cocora, Willys desde la plaza principal.'},
  montenegro:{name:'Montenegro', tag:'la casa del Parque del Café', zones:['parque'], ph:'montenegro',
    intro:'Municipio cafetero conocido por el Parque del Café, a pocos kilómetros del casco urbano. Buena base si viajas con niños y quieres estar cerca de los parques temáticos.',
    acts:[['Parque del Café','Parque temático del café: atracciones mecánicas, teleférico, show cultural y sendero por el cafetal. Ocupa todo el día.'],
      ['Parque principal','Plaza tranquila con iglesia y comida típica alrededor.'],
      ['Fincas y haciendas cafeteras','La zona está llena de fincas hotel donde se vive el proceso del café.'],
      ['Ruta a Pueblo Tapao','Corredor de restaurantes campestres, muy activo en las noches de fin de semana.']],
    how:'Buses desde el Terminal de Armenia hacia Montenegro y el Parque del Café, entre 30 y 40 minutos.'},
  quimbaya:{name:'Quimbaya', tag:'noches de velas y faroles', zones:['quimbaya'], ph:'quimbaya',
    intro:'Pueblo cercano a Panaca y famoso en todo el país por su Festival de Velas y Faroles en diciembre, cuando las calles se llenan de luces hechas a mano.',
    acts:[['Panaca','Parque agropecuario con estaciones de animales y shows. Ocupa casi todo el día.'],
      ['Festival de Velas y Faroles','Cada 7 y 8 de diciembre el pueblo compite por la calle mejor iluminada. Hay que llegar temprano.'],
      ['Parque de los Arrieros','Parque temático sobre la cultura arriera, con espectáculos y actividades para niños.'],
      ['Parque principal','Plaza con iglesia y buena comida típica alrededor, tranquila el resto del año.']],
    how:'Buses desde el Terminal de Armenia hasta Quimbaya, unos 45 minutos. Desde el pueblo hay taxis y transporte hacia Panaca.'},
  buenavista:{name:'Buenavista', tag:'el balcón del Quindío', zones:['buenavista'], ph:'buenavista2',
    intro:'El pueblo más pequeño de la ruta y el de mejor vista: todo el valle a tus pies. Es zona de cafés de origen premiados y atardeceres largos.',
    acts:[['Miradores del pueblo','Desde el casco urbano se ve el valle y las montañas. El atardecer es el plan principal.'],
      ['Café San Alberto','Uno de los cafés más premiados del país, en una colina con vista al Paisaje Cultural Cafetero. Ofrece catas.'],
      ['Tour de café','Fincas pequeñas de la zona explican el proceso completo, de la semilla a la taza.'],
      ['Parapente','Hay operadores de vuelo en parapente en la zona. Pregunta en el pueblo por horarios y clima.'],
      ['Senderos y avistamiento de aves','Caminos rurales entre cafetales y guaduales, buenos para caminar temprano.']],
    how:'Buses desde el Terminal de Armenia, alrededor de una hora por carretera de montaña. También se llega desde Calarcá.'}
};

/* ---------- LUGARES ---------- */
const PLACES = [
  {id:'cocora', name:'Valle del Cocora', zone:'cocora', town:'Salento', cat:['naturaleza'], dur:300, lat:4.638, lon:-75.487, typ:14, code:3, alt:'2.400 m aprox.', ph:['cocora','cocora4','cocora5','palmsSign'],
    tag:'donde las palmas tocan las nubes', desc:'El hogar de la palma de cera, el árbol nacional de Colombia. Senderos entre neblina, puentes colgantes, ríos y bosque de niebla.',
    how:'Primero llega a Salento. En la plaza principal toma un Willys (jeep) hacia el Valle del Cocora: el trayecto es de unos 30 minutos y salen con frecuencia durante el día.',
    tips:'Sal temprano: la neblina baja en la tarde. Usa botas o zapatos que se puedan embarrar y lleva impermeable. La caminata completa toma entre 4 y 6 horas; también puedes hacer solo el tramo de las palmas.',
    todo:['Caminata entre las palmas','Casa de los colibríes','Cabalgata por el valle','Miradores']},
  {id:'salento', name:'Salento', zone:'salento', town:'Salento', cat:['pueblo','familia'], dur:180, lat:4.637, lon:-75.570, typ:17, code:2, alt:'1.900 m aprox.', ph:['salento','salento2','salento4'],
    tag:'balcones de mil colores', desc:'Pueblo de balcones de colores y la famosa Calle Real llena de artesanías. Desde su plaza salen los Willys hacia el Valle del Cocora.',
    how:'Desde el Terminal de Transportes de Armenia salen buses a Salento con frecuencia; el viaje toma alrededor de una hora.',
    tips:'Sube al Mirador de Salento por las escaleras al final de la Calle Real. Los fines de semana y festivos hay más gente: llega antes de las 10 a. m.',
    todo:['Calle Real','Mirador de Salento','Café en la plaza','Artesanías','Tejo']},
  {id:'filandia', name:'Filandia', zone:'filandia', town:'Filandia', cat:['pueblo'], dur:180, lat:4.674, lon:-75.658, typ:18, code:2, alt:'1.900 m aprox.', ph:['filandia','filandia3','filandia5','filandia8'],
    tag:'el mirador de los atardeceres', desc:'Pueblo tranquilo y fotogénico, famoso por su cestería y por el mirador Colina Iluminada, con vista a varios departamentos.',
    how:'Desde el Terminal de Transportes de Armenia salen buses a Filandia; el viaje toma entre 45 minutos y una hora.',
    tips:'Planea estar en el mirador al atardecer. Recorre las calles alrededor de la plaza para ver los talleres de cestería.',
    todo:['Mirador Colina Iluminada','Talleres de cestería','Calles coloridas','Atardecer']},
  {id:'circasia', name:'Circasia', zone:'circasia', town:'Circasia', cat:['pueblo'], dur:120, lat:4.618, lon:-75.636, typ:19, code:2, alt:'1.750 m aprox.', ph:['circasia','bahareque'],
    tag:'auténtico pueblo cafetero', desc:'Conocido por su Cementerio Libre, un cementerio laico abierto a personas de todas las creencias, y por su ambiente de pueblo cafetero sin multitudes.',
    how:'Buses y busetas frecuentes desde Armenia; el trayecto toma unos 30 minutos. Queda de camino hacia Filandia.',
    tips:'Combínalo con Filandia el mismo día: están cerca uno del otro.',
    todo:['Cementerio Libre','Parque principal','Fincas cafeteras']},
  {id:'armenia', name:'Armenia', zone:'armenia', town:'Capital del Quindío', cat:['familia'], dur:180, lat:4.534, lon:-75.681, typ:21, code:2, alt:'1.480 m aprox.', ph:['armenia','museo','quindio'],
    tag:'la Ciudad Milagro', desc:'Capital del departamento y punto de partida ideal, con aeropuerto, comercio, parques y el Museo del Oro Quimbaya.',
    how:'Es el punto de partida del viaje. Dentro de la ciudad muévete en taxi, app o bus urbano.',
    tips:'Revisa los horarios del Museo del Oro Quimbaya antes de ir. El Parque de la Vida es ideal para caminar en la tarde.',
    todo:['Museo del Oro Quimbaya','Parque de la Vida','Plaza de Bolívar','Parque Sucre']},
  {id:'parque', name:'Parque del Café', zone:'parque', town:'Montenegro', cat:['familia'], dur:420, lat:4.540, lon:-75.771, typ:22, code:1, alt:'1.300 m aprox.', ph:['parque','parque2','parque3','casaTipica'],
    tag:'adrenalina entre cafetales', desc:'Parque temático dedicado al café, con atracciones mecánicas, teleférico, shows culturales y un sendero por el cafetal.',
    how:'Desde el Terminal de Armenia hay buses hacia Montenegro y el Parque del Café; el viaje toma entre 30 y 40 minutos.',
    tips:'Compra las entradas con anticipación en temporada alta. Llega a la apertura para aprovechar el día y lleva ropa fresca.',
    todo:['Montaña rusa','Teleférico','Show del café','Sendero ecológico']},
  {id:'quimbaya', name:'Quimbaya y Panaca', zone:'quimbaya', town:'Quimbaya', cat:['familia','pueblo'], dur:360, lat:4.623, lon:-75.763, typ:22, code:2, alt:'1.300 m aprox.', ph:['quimbaya','casaTipica'],
    tag:'noches de velas y faroles', desc:'Pueblo cercano a Panaca, el parque agropecuario, y famoso por su Festival de Velas y Faroles del 7 y 8 de diciembre.',
    how:'Buses desde el Terminal de Armenia hasta Quimbaya (unos 45 minutos). Desde el pueblo toma un taxi o transporte hacia Panaca.',
    tips:'Panaca ocupa casi todo el día: compra la entrada antes y revisa los horarios de los shows. En diciembre el pueblo se llena por el festival.',
    todo:['Panaca','Parque de los Arrieros','Parque principal','Festival de Velas (diciembre)']},
  {id:'buenavista', name:'Buenavista', zone:'buenavista', town:'Buenavista', cat:['naturaleza','pueblo'], dur:150, lat:4.360, lon:-75.740, typ:20, code:1, alt:'1.500 m aprox.', ph:['buenavista2','buenavista','genova','cafetal'],
    tag:'el balcón del Quindío', desc:'Un pueblo pequeño con miradores espectaculares sobre el valle y las montañas. Zona de cafés de origen premiados e ideal para ver el atardecer.',
    how:'Buses desde el Terminal de Armenia; el viaje toma alrededor de una hora por carretera de montaña.',
    tips:'Ve en la tarde para ver el atardecer desde los miradores. Hay opciones de vuelo en parapente: pregunta en el pueblo.',
    todo:['Miradores','Cata de café','Parapente','Atardecer']}
];

/* ---------- RESTAURANTES REALES ---------- */
const FOOD = [
  /* Salento */
  {id:'r-brunch', name:'Brunch de Salento', zone:'salento', slot:'desayuno', dur:60, ph:'calentado', dish:'Desayunos y brunch antes de salir al Cocora',
    desc:'Punto clásico de desayuno y brunch en el centro de Salento. El equipo suele orientar a los viajeros sobre rutas de caminata y cómo llegar al valle.', tips:'Queda a unas cuadras de la plaza. Ideal antes de tomar el Willys de la mañana.'},
  {id:'r-jesus', name:'Café Jesús Martín', zone:'salento', slot:'cafe', dur:45, ph:'cafeLeche', dish:'Café de especialidad del Quindío',
    desc:'Referente del café de especialidad en Salento, con café de la región en distintos métodos y un patio interior para sentarse.', tips:'Pide un método filtrado para sentir los sabores del café local. Queda cerca de la plaza principal.'},
  {id:'r-andrea', name:'Restaurante Andrea', zone:'salento', slot:'almuerzo', dur:75, ph:'trucha', dish:'Trucha en muchas preparaciones',
    desc:'Restaurante típico muy recomendado por la gente del pueblo, con una carta amplia de truchas: al ajillo, gratinada, en salsas.', tips:'A la hora del almuerzo se llena: llega antes de las 12:30.'},
  {id:'r-laurita', name:'Donde Laurita', zone:'salento', slot:'almuerzo', dur:75, ph:'comida1', dish:'Trucha arcoíris con patacón',
    desc:'Trucha arcoíris con buena sazón y varias preparaciones. Las más pedidas son la marinada con camarones y la gratinada con champiñones.', tips:'Buena opción si quieres probar la trucha en algo distinto al ajillo.'},
  {id:'r-cuesta', name:'La Cuesta de la Abuela', zone:'salento', slot:'almuerzo', dur:70, ph:'almuerzo1', dish:'Almuerzos caseros junto a la plaza',
    desc:'Cocina casera a pasos del parque principal, diagonal a la Calle Real. Trucha dorada, patacón especial y almuerzos completos.', tips:'Buena parada si estás recorriendo la Calle Real a pie.'},
  {id:'r-martina', name:'La Martina Salento', zone:'salento', slot:'cena', dur:90, ph:'chuleta', dish:'Cocina de autor para la noche',
    desc:'Propuesta más elaborada, de cocina de autor con ingredientes locales. Ambiente tranquilo, pensado para una cena con calma.', tips:'Es el plan de noche del pueblo: vale preguntar si aceptan reserva.'},
  /* Valle del Cocora */
  {id:'r-cocora', name:'Puestos del Valle del Cocora', zone:'cocora', slot:'cafe', dur:30, ph:'aguapanela', dish:'Aguapanela con queso y trucha',
    desc:'A la entrada del valle y en la zona de los Willys hay puestos y restaurantes sencillos con aguapanela con queso, café y trucha: la recarga clásica de la caminata.', tips:'Lleva efectivo: en el valle no siempre aceptan tarjeta.'},
  /* Filandia */
  {id:'r-helena', name:'Helena Adentro', zone:'filandia', slot:'almuerzo', dur:90, ph:'aborrajado', dish:'Cocina fusión en casa quindiana',
    desc:'El restaurante más conocido de Filandia, en una casa colorida con arquitectura típica y ambiente bohemio. Croquetas de plátano maduro, ceviches con frutas tropicales y el Pollo de la Abuela.', tips:'Se llena en fines de semana y festivos. Tiene buena vista desde la parte de atrás.'},
  {id:'r-jose', name:'Restaurante José Fernando', zone:'filandia', slot:'almuerzo', dur:80, ph:'empanada', dish:'Cocina colombiana en casa de 125 años',
    desc:'Cocina colombiana tradicional con toques modernos en una casa de más de un siglo. Empanadas caseras, arepas, papas de la casa y coctelería.', tips:'Fue reconocido como uno de los mejores del Eje Cafetero: buena opción para un almuerzo largo.'},
  {id:'r-mocafe', name:'MOCAFE', zone:'filandia', slot:'cafe', dur:40, ph:'cafeGranos', dish:'Café y té de la región',
    desc:'Cafetería del pueblo para el cafecito de después del almuerzo, con café de la zona y opciones de té.', tips:'Combínalo con la caminata por las calles del centro antes del mirador.'},
  {id:'r-bakuru', name:'Bakúrú', zone:'filandia', slot:'cena', dur:90, ph:'comida2', dish:'Cocina colombiana con influencias del mundo',
    desc:'Cocina colombiana mezclada con recetas de otras partes del mundo, en un espacio moderno con terraza y vista a las montañas.', tips:'Pide mesa en la terraza si quieres ver el atardecer mientras comes.'},
  {id:'r-taurus', name:'Taurus Steak House Coffee & Bar', zone:'filandia', slot:'cena', dur:85, ph:'chuleta', dish:'Carnes a la parrilla',
    desc:'La parada de carnes de Filandia: cortes a la parrilla, ambiente de bar y café.', tips:'Buena opción si vienes con hambre después de caminar todo el día.'},
  /* Armenia */
  {id:'r-constitucion', name:'Cafetería La Constitución', zone:'armenia', slot:'desayuno', dur:45, ph:'calentado', dish:'Calentado, caldos y chocolate',
    desc:'Desayuno tradicional en el centro de Armenia, junto al Parque de la Constitución: calentado, caldo de costilla, huevos, pan fresco y chocolate.', tips:'Buen plan antes de salir temprano hacia los pueblos.'},
  {id:'r-cafequindio', name:'Restaurante Café Quindío', zone:'armenia', slot:'desayuno', dur:60, ph:'cafeLeche', dish:'Brunch y café de la región',
    desc:'Homenaje al café del Quindío en pleno centro: desayunos y brunch, panadería, postres y variedad de preparaciones de café.', tips:'Buena opción si quieres llevar café molido de recuerdo.'},
  {id:'r-cuyabro', name:'El Fogón Cuyabro', zone:'armenia', slot:'almuerzo', dur:70, ph:'sancocho', dish:'Comida típica y sudados',
    desc:'Comida típica de la región junto al Parque Sucre, con menú del día y platos caseros hechos al momento. Especialistas en sudados.', tips:'Porciones grandes y ambiente de ciudad: es la opción local de toda la vida.'},
  {id:'r-estacion', name:'Estación Paraíso', zone:'armenia', slot:'almuerzo', dur:100, ph:'almuerzo3', dish:'Almuerzo campestre a las afueras',
    desc:'Restaurante campestre a unos 10 kilómetros de Armenia, premiado como uno de los mejores de la zona cafetera. Cocina regional en medio del paisaje.', tips:'Necesitas carro o taxi. Ideal para un almuerzo con calma en familia.'},
  {id:'r-fogata', name:'Restaurante La Fogata', zone:'armenia', slot:'cena', dur:95, ph:'comida1', dish:'Clásico de la ciudad, cocina de fuego',
    desc:'Uno de los restaurantes más reconocidos del Triángulo del Café, con más de cuatro décadas de historia, carta amplia y buena bodega.', tips:'Es el plan de cena formal de Armenia: pregunta por reserva en fin de semana.'},
  {id:'r-balcon', name:'Balcón del Quindío', zone:'armenia', slot:'cena', dur:80, ph:'chorizo', dish:'Parrilla y comida típica',
    desc:'Parrilla y platos tradicionales de la región, la opción para quien quiere carne y sabores locales sin complicaciones.', tips:'Buena para grupos grandes.'},
  /* Circasia */
  {id:'r-boheme', name:'La Bohême', zone:'circasia', slot:'almuerzo', dur:70, ph:'almuerzo2', dish:'Platos caseros frente al parque',
    desc:'En el parque principal de Circasia, con platos caseros y ambiente acogedor de pueblo.', tips:'Combínalo con la visita al Cementerio Libre, que queda cerca.'},
  {id:'r-robles', name:'Parador Los Robles del Quindío', zone:'circasia', slot:'almuerzo', dur:85, ph:'ajiaco', dish:'Cocina latina y criolla',
    desc:'Parador de carretera con cocina latina y española. Su plato más recomendado es la lengua en salsa criolla.', tips:'Queda sobre la vía: práctico si vas de paso hacia Filandia.'},
  {id:'r-gemha', name:'Gemha', zone:'circasia', slot:'cafe', dur:40, ph:'cafeGranos', dish:'Café de la zona en cafetería de pueblo',
    desc:'Cafetería pequeña y acogedora de Circasia, buena para una pausa de café antes de seguir la ruta.', tips:'Parada corta y tranquila entre Armenia y Filandia.'},
  {id:'r-montereal', name:'MonteReal Coffee Pub', zone:'circasia', slot:'cena', dur:75, ph:'hamburguesa', dish:'Comida informal y pub de café',
    desc:'Mezcla de café y pub con comida colombiana e informal, buena para una cena relajada en el pueblo.', tips:'Opción cómoda si te quedas a dormir en Circasia.'},
  /* Quimbaya */
  {id:'r-lulu', name:'La Pequeña Granja de Mamá Lulú', zone:'quimbaya', slot:'almuerzo', dur:110, ph:'comida1', dish:'Tilapia cocinada en guadua',
    desc:'Finca campesina y restaurante en la vereda Palermo, entre Panaca y el Parque del Café. Su plato insignia es la tilapia cocinada dentro de un tubo de guadua, con ensalada, arroz y aguacate.', tips:'Los platos fuertes se piden con reserva anticipada, avisando con al menos dos días. Confirma antes de ir.'},
  {id:'r-panacafood', name:'Puntos de comida de Panaca', zone:'quimbaya', slot:'almuerzo', dur:60, ph:'almuerzo3', dish:'Comida típica y rápida dentro del parque',
    desc:'Dentro de Panaca hay restaurantes y puestos de comida típica y rápida, así no pierdes tiempo de shows ni estaciones.', tips:'Almuerza temprano o tarde para evitar las filas del mediodía.'},
  {id:'r-quimbayaplaza', name:'Comida típica del parque de Quimbaya', zone:'quimbaya', slot:'cena', dur:70, ph:'chorizo', dish:'Asados, chorizo y arepa en el pueblo',
    desc:'Alrededor del parque principal de Quimbaya hay asaderos y restaurantes de comida típica: carne a la brasa, chorizo y arepa, ideales después de un día en Panaca.', tips:'En diciembre el pueblo se llena por el Festival de Velas y Faroles: ve temprano.'},
  /* Montenegro / Parque del Café */
  {id:'r-parquefood', name:'Restaurantes del Parque del Café', zone:'parque', slot:'almuerzo', dur:60, ph:'almuerzo1', dish:'Comida típica sin salir del parque',
    desc:'Dentro del Parque del Café hay varios restaurantes y puntos de comida, desde típica hasta rápida, para no perder tiempo de atracciones.', tips:'Almuerza antes de las 12 o después de la 2 para evitar filas.'},
  {id:'r-traviesa', name:'La Traviesa Cafetera', zone:'parque', slot:'almuerzo', dur:75, ph:'almuerzo2', dish:'Comida típica de la región',
    desc:'Restaurante de Montenegro especializado en comida típica de la región, abierto todos los días.', tips:'Buena alternativa si sales del parque con hambre y quieres comida local.'},
  {id:'r-gualandu', name:'Restaurante Gualandú', zone:'parque', slot:'cena', dur:95, ph:'comida2', dish:'Cena campestre bajo el samán',
    desc:'A un par de kilómetros del Parque del Café, sobre la vía a Pueblo Tapao. Varios ambientes, un samán iluminado en el patio, fogata, juegos para niños y música en vivo los fines de semana.', tips:'Es plan de noche: pregunta por reserva si van varios.'},
  {id:'r-asados', name:'Asados y Chorizos', zone:'parque', slot:'cena', dur:60, ph:'chorizo', dish:'Chorizos y asados de la noche',
    desc:'Parada nocturna de asados y chorizos en Montenegro, informal y rápida, con promociones entre semana.', tips:'Abre en la tarde y noche: no sirve para almuerzo.'},
  /* Buenavista */
  {id:'r-coffeehouse', name:'Coffee House Buenavista', zone:'buenavista', slot:'desayuno', dur:45, ph:'calentado', dish:'Desayuno con vista al valle',
    desc:'Cafetería del pueblo, bien valorada por viajeros, buena para desayunar antes de salir a caminar o a volar en parapente.', tips:'Buenavista es pequeño: casi todo queda a pasos del parque.'},
  {id:'r-rioazul', name:'Restaurante Río Azul', zone:'buenavista', slot:'almuerzo', dur:80, ph:'trucha', dish:'Trucha, patacones y opciones vegetarianas',
    desc:'Considerado el mejor sitio para comer en Buenavista: trucha en varios estilos, patacones y platos vegetarianos, con un balcón pequeño con vista al valle.', tips:'Pide mesa en el balcón si está libre: la vista es el plato principal.'},
  {id:'r-sanalberto', name:'Café San Alberto', zone:'buenavista', slot:'cafe', dur:60, ph:'cafeGranos', dish:'Cata de uno de los cafés más premiados',
    desc:'En una colina sobre el valle, este café de origen ofrece catas y preparaciones del grano que lo hizo famoso, con una de las mejores vistas del Paisaje Cultural Cafetero.', tips:'Ideal a media tarde, antes del atardecer. Confirma horarios de cata.'},
  {id:'r-concorde', name:'Mirador Café Concorde', zone:'buenavista', slot:'cafe', dur:60, ph:'cafeLeche', dish:'Café y platos típicos con vista de montaña',
    desc:'Sobre la carretera hacia Pijao, con vista abierta a las montañas, platos típicos colombianos y opciones vegetarianas.', tips:'Queda fuera del casco urbano: vale ir en carro o taxi.'}
];

/* ---------- HOSPEDAJES REALES ---------- */
const STAYS = [
  /* Salento */
  {id:'h-salentoreal', name:'Hotel Salento Real Eje Cafetero', zone:'salento', type:'hotel', fam:'hotel', ph:'salento2', good:['En el centro','Parejas','Familias'],
    desc:'Hotel del centro de Salento, a pasos de la plaza y la Calle Real. Buena base si quieres salir caminando a todo y tomar el Willys al Cocora temprano.', tips:'Estar en el centro se agradece en fin de semana, cuando el pueblo se llena.'},
  {id:'h-coffeetree', name:'Coffee Tree Boutique Hostel', zone:'salento', type:'hostal', fam:'hostal', ph:'salento3', good:['Mochileros','Viajar solo','Ambiente social'],
    desc:'Hostal conocido entre viajeros, con habitaciones compartidas y privadas y zonas comunes para conocer gente. A corta distancia del centro.', tips:'Buena opción si viajas solo y quieres armar planes con otros.'},
  {id:'h-piedemonte', name:'Ecohotel Piedemonte', zone:'salento', type:'ecohotel', fam:'hotel', ph:'salento5', good:['Tranquilidad','Jardín','Parejas'],
    desc:'Ecohotel de Salento con jardín y terraza, en un entorno más tranquilo que el centro pero cerca del pueblo.', tips:'Ideal si buscas dormir en silencio después de un día de caminata.'},
  {id:'h-viajero', name:'Viajero Salento Hostel', zone:'salento', type:'hostal', fam:'hostal', ph:'salento4', good:['Mochileros','Ambiente social','Grupos'],
    desc:'Hostal grande y muy popular entre viajeros internacionales, con zonas comunes amplias y actividades.', tips:'Reserva con tiempo en temporada alta: se llena.'},
  {id:'h-terrazas', name:'Terrazas de Salento', zone:'salento', type:'hotel', fam:'hotel', ph:'cocora3', good:['Vista','Parejas','Descanso'],
    desc:'Alojamiento de Salento con terrazas y vista al paisaje de montaña, pensado para descansar.', tips:'Pregunta por habitaciones con vista al valle.'},
  {id:'h-masia', name:'Riverside La Masía Ecohotel', zone:'salento', type:'ecohotel', fam:'hotel', ph:'salento5', good:['Naturaleza','Río','Familias'],
    desc:'Ecohotel a orillas de río en la zona de Salento, con jardín, terraza y bar. Entorno verde y sonido de agua.', tips:'Queda fuera del casco urbano: confirma cómo llegar si no tienes carro.'},
  {id:'h-montanablue', name:'Montaña Blue Glamping', zone:'salento', type:'glamping', fam:'especial', ph:'cocora4', good:['Glamping','Parejas','Experiencia'],
    desc:'Glamping en la zona de Salento, con zona de fogata y jacuzzi, para dormir en medio del paisaje sin renunciar a comodidades.', tips:'Plan romántico o de celebración: pocas unidades, reserva antes.'},
  /* Filandia */
  {id:'h-tukawa', name:'Tukawa Hotel', zone:'filandia', type:'hotel', fam:'hotel', ph:'filandia3', good:['En el centro','Parejas','Bien valorado'],
    desc:'Hotel bien valorado de Filandia, cómodo y cerca del centro, buena base para el mirador y los cafés del pueblo.', tips:'Filandia es pequeño: desde el centro se camina a todo.'},
  {id:'h-santamaria', name:'Hotel Boutique Santa María', zone:'filandia', type:'boutique', fam:'hotel', ph:'filandia4', good:['Boutique','Parejas','Familias'],
    desc:'Hotel boutique de Filandia, recomendado por familias y parejas, en casa de estilo tradicional del pueblo.', tips:'Buena opción si quieres algo especial sin salir del casco urbano.'},
  {id:'h-findland', name:'Find Land & a Rest', zone:'filandia', type:'boutique', fam:'hotel', ph:'filandia9', good:['Casa colonial','Diseño','Parejas'],
    desc:'Hotel boutique en una casa colonial restaurada, con el encanto de la arquitectura quindiana y espacios cuidados.', tips:'Muy fotogénico: encaja con el ambiente del pueblo.'},
  {id:'h-bidea', name:'Bidea Backpackers Hostel', zone:'filandia', type:'hostal', fam:'hostal', ph:'filandia5', good:['Mochileros','Económico','Viajar solo'],
    desc:'Hostal de ambiente relajado en Filandia, con habitaciones compartidas y privadas y buena onda viajera.', tips:'Alternativa tranquila a los hostales llenos de Salento.'},
  {id:'h-colina', name:'Hostal Colina de Lluvia', zone:'filandia', type:'hostal', fam:'hostal', ph:'filandia7', good:['Tranquilidad','Vista','Económico'],
    desc:'Hostal de Filandia bien valorado, sencillo y tranquilo, cerca del centro del pueblo.', tips:'Buena relación entre ubicación y calma.'},
  {id:'h-compadre', name:'Casa Hotel El Compadre', zone:'filandia', type:'hotel', fam:'hotel', ph:'filandia6', good:['Pueblo','Familias','Práctico'],
    desc:'Casa hotel de Filandia con habitaciones cómodas y ubicación práctica para recorrer el pueblo a pie.', tips:'Opción equilibrada entre hostal y hotel.'},
  {id:'h-balsora', name:'Hotel Campestre El Refugio de Balsora', zone:'filandia', type:'campestre', fam:'finca', ph:'filandia2', good:['Campestre','Paisaje','Descanso'],
    desc:'Hotel campestre en las afueras de Filandia, rodeado de paisaje cafetero, para quien prefiere dormir en el campo.', tips:'Necesitas transporte para entrar al pueblo en la noche.'},
  /* Armenia */
  {id:'h-armeniahotel', name:'Armenia Hotel', zone:'armenia', type:'hotel', fam:'hotel', ph:'armenia', good:['Ciudad','Familias','Acepta mascotas'],
    desc:'Hotel clásico de la ciudad, con 129 habitaciones y mobiliario en guadua y madera de la región. Admite perros y gatos.', tips:'Práctico si llegas de noche al aeropuerto o al terminal.'},
  {id:'h-balso', name:'Finca Cafetera El Balso', zone:'armenia', type:'finca', fam:'finca', ph:'cafetal2', good:['Finca cafetera','Desayuno','Tranquilidad'],
    desc:'Alojamiento rural pequeño en Armenia, de arquitectura típica, con siete habitaciones, desayuno, wifi y parqueadero.', tips:'Experiencia de finca sin alejarte de la capital.'},
  /* Circasia */
  {id:'h-bremen', name:'Casa Hotel Bremen', zone:'circasia', type:'hotel', fam:'hotel', ph:'circasia', good:['Pueblo','Bien valorado','Económico'],
    desc:'Casa hotel de Circasia, entre las mejor valoradas del pueblo, sencilla y cómoda para una noche de paso.', tips:'Circasia queda a mitad de camino entre Armenia y Filandia.'},
  {id:'h-orquideas', name:'Casa Hotel Las Orquídeas', zone:'circasia', type:'hotel', fam:'hotel', ph:'bahareque', good:['Pueblo','Tranquilidad','Parejas'],
    desc:'Casa hotel tranquila en Circasia, buena base para conocer el pueblo y las fincas cafeteras de los alrededores.', tips:'Pueblo sin multitudes: se duerme muy bien.'},
  {id:'h-casanova', name:'Casa Nova Hotel Campestre', zone:'circasia', type:'campestre', fam:'finca', ph:'cafetal', good:['Campestre','Piscina','Familias'],
    desc:'Hotel campestre en la zona de Circasia, con entorno verde y ambiente familiar.', tips:'Buena opción si viajas en carro y quieres base rural.'},
  {id:'h-paraiso', name:'Finca Hotel El Paraíso del Quindío', zone:'circasia', type:'finca', fam:'finca', ph:'cafetal2', good:['Finca cafetera','Familias','Desayuno'],
    desc:'Finca hotel de Circasia con habitaciones privadas y desayuno, en medio del paisaje cafetero.', tips:'Ideal para quedarse un par de noches y hacer tour de café.'},
  {id:'h-despertar', name:'Hotel Campestre El Despertar', zone:'circasia', type:'campestre', fam:'finca', ph:'quindio', good:['Campestre','Descanso','Cerca de Armenia'],
    desc:'Hotel campestre a pocos minutos de la vía principal, a un cuarto de hora del Museo del Oro Quimbaya.', tips:'Combina campo con cercanía a la ciudad.'},
  /* Quimbaya */
  {id:'h-machangara', name:'Finca Turística Machángara', zone:'quimbaya', type:'finca', fam:'finca', ph:'casaTipica', good:['Finca cafetera','Familias','Cerca de Panaca'],
    desc:'Hacienda cafetera muy cerca de Panaca, el Parque del Café y el Parque de los Arrieros. Favorita de familias que buscan tranquilidad y naturaleza.', tips:'Perfecta si vas a hacer dos parques en días seguidos.'},
  {id:'h-decameron', name:'Decameron Panaca', zone:'quimbaya', type:'todoincluido', fam:'especial', ph:'quimbaya', good:['Todo incluido','Familias','Al lado de Panaca'],
    desc:'Hotel todo incluido junto a Panaca, pensado para familias que quieren resolver comidas y actividades en un solo lugar.', tips:'Confirma qué incluye el plan y si la entrada al parque va aparte.'},
  {id:'h-casaquecanta', name:'Hotel Boutique La Casa que Canta', zone:'quimbaya', type:'boutique', fam:'hotel', ph:'casaTipica', good:['Boutique','Parejas','Diseño'],
    desc:'Hotel boutique de la zona de Quimbaya, con espacios cuidados y ambiente tranquilo entre cafetales.', tips:'Plan de pareja cerca de los parques temáticos.'},
  {id:'h-casanostra', name:'Finca Hotel Casa Nostra Villa Mariana', zone:'quimbaya', type:'finca', fam:'finca', ph:'cafetal', good:['Finca cafetera','Cerca de Panaca','Grupos'],
    desc:'Finca hotel a pocos kilómetros de Panaca y a unos veinte del Parque del Café, con ambiente rural y espacio para grupos.', tips:'Buena para familias grandes que viajan juntas.'},
  /* Montenegro */
  {id:'h-percal', name:'Hacienda El Percal', zone:'parque', type:'finca', fam:'finca', ph:'parque3', good:['Hacienda cafetera','A 2 km del Parque','Piscina'],
    desc:'Hacienda cafetera a unos dos kilómetros del Parque del Café, donde se vive la experiencia real de finca de café.', tips:'Ideal para llegar al parque a la apertura sin madrugar tanto.'},
  {id:'h-montecarlos', name:'Hotel Campestre Montecarlos', zone:'parque', type:'campestre', fam:'finca', ph:'montenegro', good:['Campestre','Familias','Cerca del Parque'],
    desc:'Hotel campestre de Montenegro, cerca del Parque del Café, con zonas verdes y ambiente familiar.', tips:'Opción práctica para un plan de dos días de parques.'},
  {id:'h-lapaloma', name:'Finca Hotel La Paloma', zone:'parque', type:'finca', fam:'finca', ph:'cafetal2', good:['Finca cafetera','Tranquilidad','Familias'],
    desc:'Finca hotel de la zona de Montenegro y Quimbaya, entre cafetales, bien ubicada para los parques temáticos.', tips:'Pregunta si incluyen tour de café en la misma finca.'},
  /* Buenavista */
  {id:'h-sanalbertohotel', name:'Hotel San Alberto Boutique', zone:'buenavista', type:'boutique', fam:'hotel', ph:'buenavista', good:['Boutique','Parejas','En el centro'],
    desc:'Hotel boutique en el centro de Buenavista, con pocas habitaciones y ambiente pensado para parejas, a pasos del parque y los miradores.', tips:'Buenavista es diminuto: todo queda cerca a pie.'},
  {id:'h-miradorcafe', name:'Mirador del Café Ecohostal', zone:'buenavista', type:'hostal', fam:'hostal', ph:'buenavista2', good:['Vista panorámica','Desayuno','Desconectarse'],
    desc:'Ecohostal en la vereda La Granja, pequeño (para unas doce personas), con terraza larga y vista panorámica al Paisaje Cultural Cafetero, balcón privado, wifi y desayuno.', tips:'Reserva con tiempo: hay pocas habitaciones y la vista es de las mejores del Quindío.'},
  {id:'h-lacima', name:'La Cima Eco Hotel', zone:'buenavista', type:'ecohotel', fam:'hotel', ph:'genova', good:['Vista','Pocas habitaciones','Parejas'],
    desc:'Ecohotel pequeño de Buenavista, con ocho habitaciones y entorno de montaña, cerca de las fincas de café de la zona.', tips:'Ideal para dos noches de descanso total.'},
  {id:'h-elvira', name:'Casa La Elvira', zone:'buenavista', type:'finca', fam:'finca', ph:'cafetal', good:['Casa tradicional','Desayuno','Vista al valle'],
    desc:'Casa tradicional de la zona de Buenavista, con vista al valle y desayuno incluido, para vivir el pueblo desde el campo.', tips:'Confirma cómo llegar: algunas casas quedan en vereda.'}
];

/* ---------- TOURS SUGERIDOS ---------- */
const PRESETS = [
  {name:'Clásico cafetero', days:2, desc:'Día 1 en el Valle del Cocora con trucha en Salento. Día 2 entre el café de Salento y el mirador de Filandia.',
    plan:[['r-brunch','cocora','r-cocora','r-andrea'],['salento','r-jesus','r-helena','filandia','r-bakuru']],
    stays:['h-salentoreal','h-tukawa'],
    icon:'<svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 9h13v5a6 6 0 0 1-6 6h-1a6 6 0 0 1-6-6z"/><path d="M17 11h1.5a2.5 2.5 0 0 1 0 5H17"/><path d="M8 3v3M12 3v3"/></svg>'},
  {name:'Naturaleza y miradores', days:3, desc:'Palmas de cera, cata de café con vista al valle en Buenavista y cierre en Circasia y Filandia.',
    plan:[['cocora','r-cocora','r-laurita','salento'],['buenavista','r-rioazul','r-sanalberto'],['circasia','r-gemha','r-jose','filandia','r-bakuru']],
    stays:['h-coffeetree','h-miradorcafe','h-findland'],
    icon:'<svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 20l6-10 4 6 3-4 5 8z"/></svg>'},
  {name:'En familia', days:3, desc:'Un día en el Parque del Café, otro en Panaca y el último en Salento, durmiendo en fincas cafeteras.',
    plan:[['parque','r-gualandu'],['quimbaya','r-quimbayaplaza'],['salento','r-cuesta','r-jesus']],
    stays:['h-percal','h-machangara','h-salentoreal'],
    icon:'<svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="8" cy="7" r="3"/><circle cx="17" cy="9" r="2.5"/><path d="M3 21v-2a5 5 0 0 1 10 0v2M14 21v-1.5a3.5 3.5 0 0 1 7 0V21"/></svg>'}
];

/* ---------- TABLAS ---------- */
const SLOT = {desayuno:'Desayuno', almuerzo:'Almuerzo', cafe:'Café y antojos', cena:'Cena'};
const TYPE = {hotel:'Hotel', hostal:'Hostal', boutique:'Hotel boutique', finca:'Finca cafetera', campestre:'Hotel campestre', ecohotel:'Ecohotel', glamping:'Glamping', todoincluido:'Todo incluido'};
const ZONES = ['armenia','circasia','filandia','salento','cocora','quimbaya','parque','buenavista'];
const ZXY = {armenia:[340,334], circasia:[469,183], filandia:[406,83], salento:[657,149], cocora:[894,147], parque:[140,276], quimbaya:[106,174], buenavista:[171,646]};
const ZONE_NAME = {armenia:'Armenia', circasia:'Circasia', filandia:'Filandia', salento:'Salento', cocora:'Valle del Cocora', parque:'Montenegro', quimbaya:'Quimbaya', buenavista:'Buenavista'};
const ZONE_TOWN = {armenia:'armenia', circasia:'circasia', filandia:'filandia', salento:'salento', cocora:'salento', parque:'montenegro', quimbaya:'quimbaya', buenavista:'buenavista'};
