/* ============================================================
   RUTA VERDE — CONTENIDO EN INGLÉS (parte 1)
   Pueblos, lugares, tours sugeridos, eventos y tarifas.
   Los nombres propios de negocios no se traducen.
   ============================================================ */
const EN = {
  /* ---------- PUEBLOS ---------- */
  'town-armenia':{tag:'the Miracle City', intro:'Quindío’s capital and your arrival point: it has the airport and the bus terminal with buses to every town. A good base if you want to sleep in the city and visit a different town each day.',
    acts:[['Quimbaya Gold Museum','Quimbaya goldwork collection in an award-winning building. Check hours: it closes some days.'],['Parque de la Vida','Trails, lakes and bamboo groves in the middle of the city. Great for an afternoon walk.'],['Plaza de Bolívar','The heart of the city, with the Monument to Effort.'],['Parque Sucre','Traditional area surrounded by cafés and local food.'],['Bus terminal','Buses leave here for Salento, Filandia, Circasia, Quimbaya, Montenegro, Buenavista and the southern towns.']],
    how:'It is the starting point. It has an airport (El Edén) and a bus terminal. Within the city use taxis, ride apps or city buses.'},
  'town-calarca':{tag:'the Village of the Chief', intro:'Armenia’s neighbor across the Quindío river. Home to the Quindío Botanical Garden and its butterfly house, and to Recuca, the coffee culture tour. In June it hosts the National Coffee Festival.',
    acts:[['Quindío Botanical Garden','Nature reserve with trails, a lookout, an insect zoo and one of the largest butterfly houses in the region.'],['Recuca','Coffee Culture Tour: dress as a coffee picker, pick coffee and see the whole process.'],['Main square and cathedral','A lively square and the church with pointed towers.'],['National Coffee Festival','In June: pageant, parades and concerts. The town fills up, so book ahead.']],
    how:'It sits right next to Armenia: 15 to 20 minutes by city bus or taxi from downtown.'},
  'town-circasia':{tag:'home of the Free Cemetery', intro:'A quiet coffee town half an hour from Armenia, on the way to Filandia. Perfect for a short stop: a coffee, the square and the Free Cemetery.',
    acts:[['Free Cemetery','A secular cemetery founded by freethinkers and open to people of all beliefs. The town’s best-known sight.'],['Main square and church','Real small-town life without crowds, with cafés around it.'],['Nearby coffee farms','Several farms in the area welcome visitors for coffee tours and country lunches.'],['On the way to Filandia','Circasia is on the way: combine both towns on the same day.']],
    how:'Frequent buses and minibuses from the Armenia terminal, about 30 minutes.'},
  'town-filandia':{tag:'the sunset lookout', intro:'A town of colorful streets, basket weaving and specialty coffee. Less crowded than Salento, with one of Quindío’s best sunsets from its lookout tower.',
    acts:[['Colina Iluminada lookout','Wooden tower with 360-degree views: on clear days you can see several provinces. Go at sunset.'],['Downtown streets','Houses with painted balconies and carved doors around the square. The most photogenic town in the area.'],['Basket-weaving workshops','Filandia is famous for its baskets: several workshops show how they are made.'],['Specialty cafés','A good scene for single-origin coffee and filter brews.'],['Natural lookouts','Short trails nearby with views over the Cauca river valley.']],
    how:'Buses from the Armenia terminal, 45 minutes to an hour. There is also direct transport from Salento.'},
  'town-salento':{tag:'balconies in a thousand colors', intro:'Quindío’s most visited town and the gateway to the Cocora Valley. Calle Real full of crafts, trout on every menu and Willys jeeps leaving the square.',
    acts:[['Cocora Valley','The wax palm forest, Colombia’s national tree. Willys jeeps leave from the square, about 30 minutes.'],['Calle Real','The street of crafts and cafés that climbs from the square to the lookout stairs.'],['Salento lookout','At the end of Calle Real, up a flight of steps: views over the Cocora valley and the mountains.'],['Coffee farm tour','Several farms around town show the coffee process and finish with a cup.'],['Tejo','Colombia’s national sport, with gunpowder: there are courts in town to try it.']],
    how:'Buses from the Armenia terminal every few minutes, about an hour. For Cocora, take a Willys from the main square.'},
  'town-montenegro':{tag:'home of the Coffee Park', intro:'A coffee town known for the Parque del Café, a few kilometers from the town center. A good base if you travel with kids and want to be close to the theme parks.',
    acts:[['Parque del Café','Coffee theme park: rides, cable car, cultural show and a trail through the coffee plantation. It takes the whole day.'],['Main square','A calm square with a church and local food around it.'],['Coffee farms and haciendas','The area is full of farm hotels where you can experience the coffee process.'],['Road to Pueblo Tapao','A strip of country restaurants, busy on weekend nights.']],
    how:'Buses from the Armenia terminal to Montenegro and the Parque del Café, 30 to 40 minutes.'},
  'town-quimbaya':{tag:'nights of candles and lanterns', intro:'A town near Panaca, famous across Colombia for its Festival of Candles and Lanterns in December, when the streets fill with handmade lights.',
    acts:[['Panaca','Farm theme park with animal stations and shows. It takes most of the day.'],['Festival of Candles and Lanterns','Every December 7 and 8 the town competes for the best-lit street. Arrive early.'],['Parque de los Arrieros','Theme park about the muleteer culture, with shows and activities for kids.'],['Main square','Square with a church and good local food around it, quiet the rest of the year.']],
    how:'Buses from the Armenia terminal to Quimbaya, about 45 minutes. From town there are taxis and transport to Panaca.'},
  'town-tebaida':{tag:'the airport gateway', intro:'Five minutes from El Edén airport. Warmer land of bamboo groves and meadows, with the Maravélez valley for horseback rides down to the La Vieja river.',
    acts:[['Horseback ride in the Maravélez valley','Rides of at least three hours through bamboo groves and meadows to the La Vieja river.'],['Plaza Nueva','Luis Arango Cardona park, with a food corridor and the Willys jeeps that go to rural areas.'],['Walks and cycling','Flat country roads, easier than those in the north of the province.'],['Farms and resorts','A good area to stay at a farm with a pool, close to the airport and the theme parks.']],
    how:'Frequent buses from Armenia, about 20 minutes. From the airport, five minutes by taxi.'},
  'town-cordoba':{tag:'whisper of bamboo groves', intro:'A young, quiet town surrounded by guadua bamboo. It is Quindío’s bamboo capital: guadua is studied, worked and sold here as crafts.',
    acts:[['National Center for the Study of Guadua Bamboo','Guided tour of everything related to guadua, with a bamboo house and a crafts exhibition.'],['Guadua crafts','Around the square they sell lamps, vases, instruments and furniture.'],['La Persia waterfalls','Three waterfalls in Río Verde Alto, about 22 km from town: Las Brisas, Las Mellizas and La Linda.'],['Kumis','The town’s typical fermented milk drink. Try it on the square.']],
    how:'Buses from the Armenia terminal, about an hour. For the waterfalls you need rural transport or a guide.'},
  'town-buenavista':{tag:'Quindío’s balcony', intro:'The smallest town on the route and the one with the best view: the whole valley at your feet. An area of award-winning single-origin coffee and long sunsets.',
    acts:[['Town lookouts','From town you can see the valley and the mountains. Sunset is the main event.'],['Café San Alberto','One of Colombia’s most awarded coffees, on a hill overlooking the Coffee Cultural Landscape. It offers tastings.'],['Coffee tour','Small farms in the area explain the whole process, from seed to cup.'],['Paragliding','There are paragliding operators in the area. Ask in town about times and weather.'],['Trails and birdwatching','Country roads between coffee plants and bamboo, good for an early walk.']],
    how:'Buses from the Armenia terminal, about an hour on a mountain road. You can also get there from Calarcá.'},
  'town-pijao':{tag:'the town without hurry', intro:'In 2014 it became the first town in Latin America to join the Cittaslow network of “slow” towns. A square of pastel façades, balconies full of flowers and misty mountains all around.',
    acts:[['Main square','Sit and watch the town go by, with coffee from the nearby mountains.'],['Nature trails','Guided walks to Tarapacá hill, La Mariela lookout and the Valley of the Butterflies.'],['Chilí páramo','A high-mountain expedition for experienced hikers. Only with a local guide.'],['Zero-kilometer cooking','Many places cook with produce from the town’s own farmers.']],
    how:'About 40 km south of Armenia. Buses from the Armenia terminal; the road winds through coffee farms and mountains. For guides and tours, ask at the town hall.'},
  'town-genova':{tag:'Quindío’s little Antioquian town', intro:'The southernmost town and one of the least visited. Restored colonial façades, very friendly people and mountains for nature and adventure tourism.',
    acts:[['Main square','Houses from the Antioquian colonization with newly restored façades.'],['Farmers’ market','Sundays on the main square: fruit, cheese and produce from the countryside.'],['Nature and adventure','Walks and rural tourism in the mountains around town.'],['Country lookouts','Country restaurants with panoramic canyon views.']],
    how:'Buses from the Armenia terminal heading south. It is the longest ride on the route: allow about an hour and a half.'},

  /* ---------- LUGARES ---------- */
  cocora:{town:'Salento', tag:'where the palms touch the clouds', desc:'Home of the wax palm, Colombia’s national tree. Trails through the mist, hanging bridges, rivers and cloud forest.',
    how:'First get to Salento. From the main square take a Willys jeep to the Cocora Valley: the ride takes about 30 minutes and they leave often during the day.',
    tips:'Leave early: mist rolls in during the afternoon. Wear boots or shoes that can get muddy and bring a rain jacket. The full loop takes 4 to 6 hours; you can also walk just the palm section.',
    todo:['Walk among the palms','Hummingbird house','Horseback ride through the valley','Lookouts']},
  salento:{town:'Salento', tag:'balconies in a thousand colors', desc:'A town of colorful balconies and the famous Calle Real full of crafts. Willys jeeps to the Cocora Valley leave from its square.',
    how:'Buses leave the Armenia bus terminal for Salento often; the ride takes about an hour.',
    tips:'Climb to the Salento lookout by the stairs at the end of Calle Real. Weekends and holidays are busier: arrive before 10 a.m.',
    todo:['Calle Real','Salento lookout','Coffee on the square','Crafts','Tejo']},
  filandia:{town:'Filandia', tag:'the sunset lookout', desc:'A calm, photogenic town famous for its basket weaving and the Colina Iluminada lookout, with views over several provinces.',
    how:'Buses leave the Armenia bus terminal for Filandia; the ride takes 45 minutes to an hour.',
    tips:'Plan to be at the lookout at sunset. Walk the streets around the square to see the basket-weaving workshops.',
    todo:['Colina Iluminada lookout','Basket-weaving workshops','Colorful streets','Sunset']},
  circasia:{town:'Circasia', tag:'a genuine coffee town', desc:'Known for its Free Cemetery, a secular cemetery open to people of all beliefs, and for its crowd-free coffee-town feel.',
    how:'Frequent buses and minibuses from Armenia; about 30 minutes. It is on the way to Filandia.',
    tips:'Combine it with Filandia on the same day: they are close to each other.',
    todo:['Free Cemetery','Main square','Coffee farms']},
  armenia:{town:'Quindío capital', tag:'the Miracle City', desc:'The provincial capital and an ideal starting point, with an airport, shops, parks and the Quimbaya Gold Museum.',
    how:'It is where the trip starts. Within the city use taxis, ride apps or city buses.',
    tips:'Check the Quimbaya Gold Museum’s hours before going. Parque de la Vida is great for an afternoon walk.',
    todo:['Quimbaya Gold Museum','Parque de la Vida','Plaza de Bolívar','Parque Sucre']},
  parque:{town:'Montenegro', tag:'thrills among coffee plants', desc:'A coffee theme park with rides, a cable car, cultural shows and a trail through the coffee plantation.',
    how:'Buses from the Armenia terminal go to Montenegro and the Parque del Café; the ride takes 30 to 40 minutes.',
    tips:'Buy tickets ahead in high season. Arrive at opening time to make the most of the day and wear light clothes.',
    todo:['Roller coaster','Cable car','Coffee show','Nature trail']},
  quimbaya:{town:'Quimbaya', tag:'nights of candles and lanterns', desc:'A town near Panaca, the farm theme park, famous for its Festival of Candles and Lanterns on December 7 and 8.',
    how:'Buses from the Armenia terminal to Quimbaya (about 45 minutes). From town, take a taxi or transport to Panaca.',
    tips:'Panaca takes most of the day: buy your ticket ahead and check show times. In December the town fills up for the festival.',
    todo:['Panaca','Parque de los Arrieros','Main square','Candle Festival (December)']},
  buenavista:{town:'Buenavista', tag:'Quindío’s balcony', desc:'A small town with spectacular lookouts over the valley and mountains. Home of award-winning coffee and perfect for sunset.',
    how:'Buses from the Armenia terminal; the ride takes about an hour on a mountain road.',
    tips:'Go in the afternoon to watch the sunset from the lookouts. There is paragliding: ask in town.',
    todo:['Lookouts','Coffee tasting','Paragliding','Sunset']},
  museo:{town:'Armenia', tag:'the gold of the Quimbaya people', desc:'A Banco de la República museum with goldwork and pottery from the Quimbaya culture, in an award-winning brick-and-water building.',
    how:'It is in northern Armenia, on Avenida Bolívar. Taxi or city bus from downtown.',
    tips:'Check hours and closing days before you go. A good plan for a rainy afternoon.',
    todo:['Goldwork gallery','The building’s architecture','Gardens']},
  jardin:{town:'Calarcá', tag:'butterflies in the city', desc:'A nature reserve inside Calarcá with trails, a lookout, an insect zoo and one of the largest butterfly houses in the region.',
    how:'From Armenia, city bus or taxi to Calarcá, about 20 minutes.',
    tips:'Go on a sunny morning: butterflies are more active. Visits are usually guided.',
    todo:['Butterfly house','Lookout','Insect zoo','Trails']},
  recuca:{town:'Calarcá', tag:'live the coffee harvest', desc:'The Coffee Culture Tour: a hands-on tour of the whole coffee process where you dress as a picker and join the harvest.',
    how:'It is in rural Calarcá. The easiest way is by taxi, or book the tour with transport included.',
    tips:'Book ahead and confirm tour times. Wear closed shoes.',
    todo:['Coffee picking','Picker outfit','How coffee is processed']},
  calarca:{town:'Quindío', tag:'the Village of the Chief', desc:'Armenia’s neighboring city, with a lively square, a cathedral with pointed towers and the National Coffee Festival every June.',
    how:'City bus or taxi from Armenia, 15 to 20 minutes.',
    tips:'Combine it with the Botanical Garden on the same day.',
    todo:['Main square','Cathedral','View toward Armenia']},
  pijao:{town:'Quindío', tag:'Latin America’s first slow town', desc:'A Cittaslow town since 2014: a square of pastel façades, flower-filled balconies and mountain trails to lookouts and cloud forests.',
    how:'Buses from the Armenia terminal, about 40 km south.',
    tips:'Take it slow: that is the whole idea. For long hikes hire a local guide; ask at the town hall.',
    todo:['Main square','La Mariela lookout','Tarapacá hill','Valley of the Butterflies']},
  genova:{town:'Quindío', tag:'Quindío’s little Antioquian town', desc:'Quindío’s southernmost town: restored colonial façades, a farmers’ market on Sundays and mountains to walk.',
    how:'Buses from the Armenia terminal, about an hour and a half.',
    tips:'Go on a Sunday for the farmers’ market on the square.',
    todo:['Main square','Farmers’ market','Country walks']},
  cordoba:{town:'Quindío', tag:'whisper of bamboo groves', desc:'Quindío’s bamboo capital: a guadua bamboo study center, crafts around the square and waterfalls up in the hills.',
    how:'Buses from the Armenia terminal, about an hour.',
    tips:'Ask for the National Center for the Study of Guadua Bamboo and try the kumis.',
    todo:['Guadua Bamboo Center','Crafts','La Persia waterfalls','Kumis']},
  tebaida:{town:'La Tebaida', tag:'horseback rides to the La Vieja river', desc:'A warm town next to the airport, with horseback rides through the Maravélez valley among bamboo and meadows down to the La Vieja river.',
    how:'Frequent buses from Armenia, about 20 minutes. From the airport, five minutes by taxi.',
    tips:'Rides last at least three hours: bring a cap, sunscreen and water.',
    todo:['Ride in Maravélez','La Vieja river','Plaza Nueva']},

  /* ---------- TOURS SUGERIDOS ---------- */
  preset0:{name:'Coffee classic', desc:'Day 1 in the Cocora Valley with trout in Salento. Day 2 between Salento’s coffee and Filandia’s lookout.'},
  preset1:{name:'Nature and lookouts', desc:'Wax palms, a coffee tasting with valley views in Buenavista, and a finish in Circasia and Filandia.'},
  preset2:{name:'Family trip', desc:'One day at the Parque del Café, another at Panaca and the last in Salento, sleeping on coffee farms.'},

  /* ---------- EVENTOS ---------- */
  ev0:{when:'June', name:'National Coffee Festival', desc:'National Coffee Pageant, parades and concerts in Calarcá during the second half of June.'},
  ev1:{when:'October', name:'Armenia Festival and Yipao Parade', desc:'Anniversary festivities in the first half of October. The Yipao Parade shows Willys jeeps loaded up to the roof.'},
  ev2:{when:'December 7 and 8', name:'Festival of Candles and Lanterns', desc:'Quimbaya’s streets compete for the best handmade lighting. Arrive early.'},
  ev3:{when:'Every Sunday', name:'Génova farmers’ market', desc:'Produce from the countryside on the main square.'},
  ev4:{when:'Holy Week and holidays', name:'High season', desc:'Salento, Cocora and the parks fill up. Book your stay ahead and start early.'},

  /* ---------- TARIFAS ---------- */
  fare0:{how:'Bus from the terminal', time:'1 h', price:'from $5,300'},
  fare1:{how:'Bus from the terminal', time:'45 min to 1 h', price:'$7,200 to $8,000'},
  fare2:{how:'Bus', time:'20 min', price:'about $5,700'},
  fare3:{how:'Bus from the terminal', time:'45 min', price:'about $6,900'},
  fare4:{how:'Willys jeep from the square', time:'30 min', price:'$5,000 to $10,000 each way'},
  fare5:{route:'Cocora trails', how:'Crossing private farms', time:'—', price:'$5,000 to $6,000 per checkpoint, cash'},
  fare6:{route:'Horseback ride in Cocora', how:'Operators in the valley', time:'depends on the route', price:'from $60,000'}
};
