/* ============================================================
   RUTA VERDE — MÁS FOTOS
   Fotos con licencia libre de Wikimedia Commons, elegidas a mano: más fotos de cada lugar
   turístico, fotos de platos típicos y del entorno de cada pueblo.
   `of` marca las fotos que son del propio negocio (se muestran primero con la etiqueta "Foto real").
   GALLERY dice qué fotos extra lleva cada lugar, restaurante u hospedaje (además de su foto principal).
   Para poner fotos propias de un negocio: guárdalas en img/ (nombre-s.webp y nombre-l.webp),
   agrégalas aquí en PHOTOS con of:'id-del-negocio' y ponlas en su lista de GALLERY.
   ============================================================ */
Object.assign(PHOTOS, {
  cparque27:{f:'Eje cafetero.jpg', t:'Mirador del Parque del Café', by:'Chica Eje Cafetero', lic:'CC BY-SA 4.0'},
  cparque19:{f:'Atraccion Parque del Café.jpg', t:'Montaña rusa del Parque del Café', by:'Juliancufiño', lic:'CC BY-SA 4.0'},
  cparque12:{f:'Coffee process museum cable cars.jpg', t:'Teleférico del Parque del Café', by:'Pascaweb at English Wikipedia', lic:'Dominio público'},
  cparque23:{f:'Baile tipico folcklorico parque del cafe.jpg', t:'Show folclórico en el Parque del Café', by:'Franciscokarriere', lic:'CC BY-SA 4.0'},
  cparque17:{f:'Bosque de guadua en el Parque del Cafe-Colombia.jpg', t:'Bosque de guadua, Parque del Café', by:'Diego Cambiaso', lic:'CC BY-SA 2.0'},
  cparque26:{f:'Estacion de telesillas parque del cafe, colombia.jpg', t:'Telesillas del Parque del Café', by:'Franciscokarriere', lic:'CC BY-SA 4.0'},
  cparque9:{f:'Bridge looks like Burning Man.jpg', t:'Puente colgante, Parque del Café', by:'Joshua Heller', lic:'CC BY 2.0'},
  cparque35:{f:'Estación Montenegro Parque del Café.jpg', t:'Estación Montenegro, Parque del Café', by:'CamiloB4', lic:'CC BY-SA 4.0'},
  cpanaca2:{f:'Pony Col.JPG', t:'Caballo pony en Panaca', by:'Sgiraldoa', lic:'CC BY 2.5'},
  cpanaca4:{f:'Avestruz del Café.jpg', t:'Avestruces en Panaca', by:'HaseyJDBS', lic:'CC BY-SA 4.0'},
  cpanaca5:{f:'Puesto informacion turistica.jpg', t:'Punto de información de Panaca', by:'Franciscokarriere', lic:'CC BY-SA 4.0'},
  csalento4:{f:'Café Jesús Martín, Salento 01.jpg', t:'Café Jesús Martín, Salento', by:'Bernard Gagnon', lic:'CC BY-SA 4.0', of:'r-jesus'},
  csalento5:{f:'Café Jesús Martín, Salento 02.jpg', t:'Café Jesús Martín, Salento', by:'Bernard Gagnon', lic:'CC BY-SA 4.0', of:'r-jesus'},
  csalento0:{f:'Callerealsalento.JPG', t:'Calle Real de Salento', by:'Sebasmrodriguez', lic:'CC BY-SA 3.0'},
  csalento7:{f:'Casa de la Pava, Salento 02.jpg', t:'Casa de la Pava, Salento', by:'Bernard Gagnon', lic:'CC BY-SA 4.0'},
  csalento10:{f:'Calle 5, Salento 03.jpg', t:'Calle 5, Salento', by:'Bernard Gagnon', lic:'CC BY-SA 4.0'},
  csalento11:{f:'Calle 5, Salento 04.jpg', t:'Balcones de la Calle 5, Salento', by:'Bernard Gagnon', lic:'CC BY-SA 4.0'},
  csalento21:{f:'Iglesia de Nuestra Señora del Carmen, Salento 05.jpg', t:'Iglesia de Nuestra Señora del Carmen, Salento', by:'Bernard Gagnon', lic:'CC BY-SA 4.0'},
  ccocora0:{f:'Ceroxylon quindiuense cocora.jpg', t:'Palmas de cera, Valle del Cocora', by:'Diegotorquemada', lic:'CC BY 3.0'},
  ccocora1:{f:'Ambiente turistico-Valle del Cocora.jpg', t:'Columpio en el Valle del Cocora', by:'Chica Eje Cafetero', lic:'CC BY-SA 4.0'},
  cbirds28:{f:'Florisuga mellivora - Colibrí collarejo - White naked Jacobin.jpg', t:'Colibrí collarejo del Quindío', by:'Alejandro Bayer Tamayo', lic:'Dominio público'},
  cbirds35:{f:'Carriquí verdeamarillo junio 2025.jpg', t:'Carriquí verdeamarillo', by:'AmiGueko', lic:'CC BY-SA 4.0'},
  cbirds32:{f:'Colinus cristatus - Perdiz crestada.jpg', t:'Perdiz crestada', by:'Alejandro Bayer Tamayo', lic:'Dominio público'},
  cjardin3:{f:'Mariposario, Jardín Botánico del Quindío.JPG', t:'Mariposario del Jardín Botánico del Quindío', by:'Karolynaroca', lic:'CC BY-SA 3.0'},
  cjardin4:{f:'Q calarca mariposario.JPG', t:'Sendero del Jardín Botánico, Calarcá', by:'Mama', lic:'CC BY-SA 4.0'},
  cjardin6:{f:'Qc mariposario calarca.JPG', t:'Cascada del Jardín Botánico, Calarcá', by:'Mama', lic:'CC BY-SA 4.0'},
  cjardin7:{f:'M mariposario calarca.JPG', t:'Puente colgante del Jardín Botánico', by:'Mama', lic:'CC BY-SA 4.0'},
  cjardin0:{f:'Passiflora foetida (1).jpg', t:'Flor de pasiflora', by:'Caya!!', lic:'CC BY 2.0'},
  cmuseo0:{f:'Museo Quimbaya Armenia Quindio.JPG', t:'Museo del Oro Quimbaya, Armenia', by:'Jhon James Gutierrez Gil', lic:'CC BY-SA 3.0'},
  cmuseo2:{f:'Poporo quimbaya museo del oro.jpg', t:'Poporo quimbaya del museo', by:'Rivera Guzman Cristian Santiago', lic:'CC BY-SA 4.0'},
  cfilandia0:{f:'El mirador del Quindío.jpg', t:'Mirador Colina Iluminada, Filandia', by:'LopezRoaJuan', lic:'CC BY-SA 3.0'},
  cfilandia32:{f:'Building in Filandia, 01.jpg', t:'Casa de colores, Filandia', by:'Bernard Gagnon', lic:'CC BY-SA 4.0'},
  cfilandia2:{f:'Green (249804949).jpeg', t:'Montañas de Filandia', by:'Pedro Agudelo Gaona', lic:'CC BY 3.0'},
  cfilandia35:{f:'Filandia, Quindío.jpg', t:'Iglesia de Filandia', by:'David Argemiro', lic:'CC BY-SA 4.0'},
  crest23:{f:'La Casa del Pandebono, Filandia.jpg', t:'La Casa del Pandebono, Filandia', by:'Bernard Gagnon', lic:'CC BY-SA 4.0'},
  ccircasia2:{f:'Circasia Ago 2017 (8).jpg', t:'Cementerio Libre de Circasia', by:'Darthvader2', lic:'CC BY-SA 4.0'},
  ccircasia12:{f:'Circasia Ago 2017 (19).jpg', t:'Jardín del Cementerio Libre', by:'Darthvader2', lic:'CC BY-SA 4.0'},
  ccircasia10:{f:'Circasia Ago 2017 (28).jpg', t:'Mirador de Circasia', by:'Darthvader2', lic:'CC BY-SA 4.0'},
  ccircasia29:{f:'DJI Municipio de Circasia.jpg', t:'Circasia desde el aire', by:'Cabt2020', lic:'CC BY-SA 4.0'},
  ccircasia30:{f:'Restaurantes en Circasia.jpg', t:'Restaurantes en Circasia', by:'Forest899', lic:'CC BY-SA 4.0'},
  ccircasia23:{f:'Tarde en Circasia (15006752100).jpg', t:'Tarde en Circasia', by:'Alejandro Bayer Tamayo from Armenia, Colombia', lic:'CC BY-SA 2.0'},
  ccalarca9:{f:'Casa calarqueña estilo antioqueño.jpg', t:'Casa calarqueña', by:'CamiloB4', lic:'CC BY-SA 4.0'},
  ccalarca10:{f:'Calle 40 de Calarcá.jpg', t:'Calle 40 de Calarcá', by:'CamiloB4', lic:'CC BY-SA 4.0'},
  ccalarca15:{f:'Calarcá - Casa de los Tellez.jpg', t:'Casa de los Téllez, Calarcá', by:'XalD', lic:'CC BY-SA 4.0'},
  ccalarca3:{f:'Calarca Quindio.jpg', t:'Centro de Calarcá', by:'Darthvader2', lic:'CC BY-SA 4.0'},
  ccalarca12:{f:'Calarca, Quindio.jpg', t:'Cascada cerca de Calarcá', by:'Carolina1510', lic:'CC BY-SA 4.0'},
  cgenova2:{f:'Parque principal genova.jpg', t:'Parque principal de Génova', by:'Infogenova', lic:'CC BY-SA 4.0'},
  cgenova3:{f:'Cascada en el Corazón - Génova (Quindío) (15318220247).jpg', t:'Cascada en el Corazón, Génova', by:'Alejandro Bayer Tamayo from Armenia, Colombia', lic:'CC BY-SA 2.0'},
  cgenova5:{f:'Cascada en el Corazón - Génova (Quindío) (15504419362).jpg', t:'Cascada en el Corazón, Génova', by:'Alejandro Bayer Tamayo from Armenia, Colombia', lic:'CC BY-SA 2.0'},
  carmenia0:{f:'Catedral de armenia.jpg', t:'Catedral de Armenia', by:'Jorgecuyabro', lic:'CC0'},
  carmenia7:{f:'Catedral de la Inmaculada Concepción, Armenia - interior.jpg', t:'Interior de la Catedral de Armenia', by:'XalD', lic:'CC BY-SA 4.0'},
  carmenia8:{f:'Día cálido.jpg', t:'Plaza de la Catedral, Armenia', by:'Valencia 1706', lic:'CC BY-SA 4.0'},
  ctebaida1:{f:'La Tebaida (1), Quindío, Colombia.JPG', t:'Iglesia de La Tebaida', by:'Hoako', lic:'CC BY-SA 4.0'},
  ctebaida2:{f:'The Heaven (248884275).jpeg', t:'Paisaje de La Tebaida', by:'Pedro Agudelo Gaona', lic:'CC BY 3.0'},
  ccordoba1:{f:'CABALGATA AL ATARDECER.jpg', t:'Cabalgata al atardecer, Córdoba', by:'Jose Montoya', lic:'CC BY-SA 4.0'},
  cbuenavista1:{f:'Buenavista Ene 2016 (57).JPG', t:'Iglesia de Buenavista', by:'Darthvader2', lic:'CC BY-SA 4.0'},
  cmontenegro0:{f:'Estacion ferrocarril Montenegro Quindio.JPG', t:'Antigua estación del ferrocarril, Montenegro', by:'Jhon James Gutierrez Gil', lic:'CC BY-SA 3.0'},
  cbandeja1:{f:'Bandeja paisa 30062011.jpg', t:'Bandeja paisa', by:'Dtarazona', lic:'CC BY-SA 3.0'},
  cbandeja2:{f:'Bandeja paisa del Chocolos 30062011.jpg', t:'Bandeja paisa', by:'Dtarazona', lic:'CC BY-SA 3.0'},
  cbandeja8:{f:'Bandeja paisa, plato Colombiano.jpg', t:'Bandeja paisa', by:'Wilfredor', lic:'CC0'},
  cbandeja9:{f:'Bandeja Paisa.jpg', t:'Bandeja paisa', by:'PapiPijuan', lic:'CC BY-SA 4.0'},
  cbandeja15:{f:'باندیخا بایسا.jpg', t:'Bandeja paisa', by:'Harham999', lic:'CC BY-SA 4.0'},
  carepa8:{f:'Arepas con chorizo.jpg', t:'Arepas con chorizo', by:'William Neuheisel from DC, US', lic:'CC BY 2.0'},
  carepa14:{f:'Kolumbianische Arepas mit Käsefüllung.jpg', t:'Arepa rellena de queso', by:'Superhomi912', lic:'CC BY-SA 4.0'},
  carepa19:{f:'Chocolate, arepa, quesito y mote.jpg', t:'Chocolate, arepa y quesito', by:'Eddy Milfort', lic:'CC BY-SA 2.0'},
  carepa26:{f:'Colombian classic - hot chocolate with arepa and cheese (in porcelain with pink flowers).jpg', t:'Chocolate con arepa y queso', by:'Quinn Comendant', lic:'CC BY-SA 2.0'},
  cpatacon6:{f:'Patacones - Barranquilla.jpg', t:'Patacones', by:'Jdvillalobos', lic:'CC BY 3.0'},
  cpatacon23:{f:'Grilled yellow snapper with green papaya salad and tostones.jpg', t:'Pescado con patacones', by:'Jeffrey Bary', lic:'CC BY 2.0'},
  cpatacon25:{f:'Comida de la Playa de Santa Verónica.jpg', t:'Pescado frito con patacones y arroz', by:'PapiPijuan', lic:'CC BY-SA 4.0'},
  csopas10:{f:'Sancocho 1.jpg', t:'Sancocho', by:'Caldobasico', lic:'CC BY-SA 4.0'},
  csopas11:{f:'Caldo de costilla Paisa.jpg', t:'Caldo de costilla', by:'Xemenendura', lic:'CC BY-SA 4.0'},
  csopas1:{f:'Caldo de Costilla.jpg', t:'Caldo de costilla con arepa', by:'Peter Angritt', lic:'CC BY-SA 3.0'},
  csopas3:{f:'20160102 Panachi 03.jpg', t:'Sopa típica colombiana', by:'Racso', lic:'CC BY-SA 4.0'},
  ccafe16:{f:'Clumps of coffee berries growing on a tree, by Brian Smith.jpg', t:'Granos de café maduros', by:'U. S. Fish and Wildlife Service - Northeast Region', lic:'Dominio público'},
  ccafe24:{f:'Colombian coffee bags.jpg', t:'Sacos de café colombiano', by:'Felipe Quijano', lic:'CC BY-SA 4.0'},
  ccafe31:{f:'Degustación de Café. Colombia.jpg', t:'Degustación de café', by:'Xemenendura', lic:'CC BY-SA 4.0'},
  ccafe33:{f:'Café colombiano Santa Clara.jpg', t:'Taza de café colombiano', by:'Xemenendura', lic:'CC BY-SA 4.0'},
  ccarnes0:{f:'Asado Bogotano.jpg', t:'Asado', by:'No machine-readable author provided. Tequendamia assumed (ba', lic:'Dominio público'},
  ccarnes8:{f:'Fiambre de Guacarí 04.jpg', t:'Fiambre en hoja de plátano', by:'Remux', lic:'CC BY-SA 4.0'},
  ccarnes1:{f:'Lechona.JPG', t:'Lechona', by:'Tamorlan', lic:'CC BY-SA 3.0'},
  cempanada7:{f:'Empanadas 1.jpg', t:'Empanadas', by:'Caldobasico', lic:'CC BY-SA 4.0'},
  cempanada8:{f:'Empanada colombiana.jpg', t:'Empanadas colombianas', by:'Francesc Fort', lic:'CC BY-SA 4.0'},
  cempanada3:{f:'Empanada tray.jpg', t:'Empanadas recién hechas', by:'Siliconred', lic:'CC BY-SA 4.0'},
  cpostres4:{f:'Home-made buñuelos.JPG', t:'Buñuelos', by:'Mtam', lic:'Dominio público'},
  cpostres2:{f:'A plate of Colombian Natilla.JPG', t:'Natilla', by:'Mtam', lic:'Dominio público'},
  cpostres5:{f:'Postre de Guanábana.jpg', t:'Postre de guanábana', by:'Peter Angritt', lic:'CC BY-SA 3.0'},
  cchocolate2:{f:'Chocolate caliente con queso 1.jpg', t:'Chocolate caliente con queso', by:'Caldobasico', lic:'CC BY-SA 4.0'},
  cchocolate3:{f:'Chocolate caliente con queso 2.jpg', t:'Chocolate caliente con queso', by:'Caldobasico', lic:'CC BY-SA 4.0'},
  caguapanela0:{f:'Agua Panela con Queso Fresco at La Puerta Falsa (5617496209).jpg', t:'Aguapanela con queso', by:'William Neuheisel from DC, US', lic:'CC BY 2.0'},
  crest33:{f:'Calentao Sancho Paixa.jpg', t:'Calentado paisa', by:'Xemenendura', lic:'CC BY-SA 4.0'}
});

const GALLERY = {
  "cocora":['ccocora0', 'ccocora1', 'cbirds28', 'cbirds35'],
  "salento":['csalento0', 'csalento7', 'csalento10', 'csalento11', 'csalento21'],
  "filandia":['cfilandia0', 'cfilandia32', 'cfilandia35', 'cfilandia2', 'crest23'],
  "circasia":['ccircasia2', 'ccircasia12', 'ccircasia10', 'ccircasia29', 'ccircasia23'],
  "armenia":['carmenia0', 'carmenia7', 'carmenia8'],
  "parque":['cparque27', 'cparque19', 'cparque12', 'cparque23', 'cparque17', 'cparque26', 'cparque9', 'cparque35'],
  "quimbaya":['cpanaca2', 'cpanaca4', 'cpanaca5'],
  "buenavista":['cbuenavista1', 'ccafe31'],
  "museo":['cmuseo0', 'cmuseo2'],
  "jardin":['cjardin3', 'cjardin4', 'cjardin6', 'cjardin7', 'cjardin0', 'cbirds32'],
  "recuca":['ccafe16', 'ccafe24'],
  "calarca":['ccalarca9', 'ccalarca15', 'ccalarca10', 'ccalarca3', 'ccalarca12'],
  "genova":['cgenova2', 'cgenova3', 'cgenova5'],
  "cordoba":['ccordoba1'],
  "tebaida":['ctebaida1', 'ctebaida2'],
  "r-brunch":['crest33', 'cchocolate2', 'carepa19', 'carepa26', 'csalento0', 'csalento10'],
  "r-jesus":['csalento5', 'csalento4', 'ccafe31', 'ccafe33', 'ccafe24', 'ccafe16'],
  "r-andrea":['trucha', 'cpatacon25', 'cpatacon23', 'cpatacon6', 'csalento0', 'csalento10'],
  "r-laurita":['trucha', 'cpatacon25', 'cpatacon23', 'cpatacon6', 'csalento0', 'csalento10'],
  "r-cuesta":['cbandeja1', 'cbandeja8', 'cbandeja9', 'cbandeja2', 'cbandeja15', 'csopas10'],
  "r-martina":['cbandeja8', 'crest33', 'csalento0', 'csalento10'],
  "r-cocora":['trucha', 'cpatacon25', 'cpatacon23', 'cpatacon6', 'ccocora0', 'ccocora1'],
  "r-helena":['cbandeja8', 'crest33', 'cfilandia32', 'crest23'],
  "r-jose":['cbandeja1', 'cbandeja8', 'cbandeja9', 'cbandeja2', 'cbandeja15', 'csopas10'],
  "r-mocafe":['ccafe31', 'ccafe33', 'ccafe24', 'ccafe16', 'cfilandia32', 'crest23'],
  "r-bakuru":['cbandeja1', 'cbandeja8', 'cbandeja9', 'cbandeja2', 'cbandeja15', 'csopas10'],
  "r-taurus":['carepa8', 'ccarnes0', 'cfilandia32', 'crest23'],
  "r-constitucion":['ccafe31', 'ccafe33', 'ccafe24', 'ccafe16', 'carmenia8', 'carmenia0'],
  "r-cafequindio":['ccafe31', 'ccafe33', 'ccafe24', 'ccafe16', 'carmenia8', 'carmenia0'],
  "r-cuyabro":['csopas10', 'csopas11', 'csopas1', 'csopas3', 'carmenia8', 'carmenia0'],
  "r-estacion":['cbandeja1', 'cbandeja8', 'cbandeja9', 'cbandeja2', 'cbandeja15', 'csopas10'],
  "r-fogata":['cbandeja8', 'crest33', 'carmenia8', 'carmenia0'],
  "r-balcon":['carepa8', 'ccarnes0', 'cbandeja1', 'cbandeja8', 'cbandeja9', 'cbandeja2'],
  "r-boheme":['cbandeja1', 'cbandeja8', 'cbandeja9', 'cbandeja2', 'cbandeja15', 'csopas10'],
  "r-robles":['cbandeja1', 'cbandeja8', 'cbandeja9', 'cbandeja2', 'cbandeja15', 'csopas10'],
  "r-gemha":['ccafe31', 'ccafe33', 'ccafe24', 'ccafe16', 'ccircasia30', 'ccircasia23'],
  "r-montereal":['ccafe31', 'ccafe33', 'ccafe24', 'ccafe16', 'ccircasia30', 'ccircasia23'],
  "r-lulu":['cpatacon23', 'cpatacon25', 'cpatacon6', 'cpanaca5'],
  "r-panacafood":['cbandeja1', 'cbandeja8', 'cbandeja9', 'cbandeja2', 'cbandeja15', 'csopas10'],
  "r-quimbayaplaza":['carepa19', 'carepa14', 'carepa8', 'cchocolate3', 'cpanaca5'],
  "r-parquefood":['ccafe31', 'ccafe33', 'ccafe24', 'ccafe16', 'cparque17', 'cmontenegro0'],
  "r-traviesa":['ccafe31', 'ccafe33', 'ccafe24', 'ccafe16', 'cparque17', 'cmontenegro0'],
  "r-gualandu":['cbandeja1', 'cbandeja8', 'cbandeja9', 'cbandeja2', 'cbandeja15', 'csopas10'],
  "r-asados":['carepa8', 'ccarnes0', 'cparque17', 'cmontenegro0'],
  "r-coffeehouse":['crest33', 'cchocolate2', 'carepa19', 'carepa26', 'cbuenavista1', 'buenavista2'],
  "r-rioazul":['trucha', 'cpatacon25', 'cpatacon23', 'cpatacon6', 'cbuenavista1', 'buenavista2'],
  "r-sanalberto":['ccafe31', 'ccafe33', 'ccafe24', 'ccafe16', 'cbuenavista1', 'buenavista2'],
  "r-concorde":['ccafe31', 'ccafe33', 'ccafe24', 'ccafe16', 'cbuenavista1', 'buenavista2'],
  "r-casabuho":['hamburguesa', 'carepa8', 'ccalarca9', 'ccalarca15'],
  "r-calarcaplaza":['ccafe31', 'ccafe33', 'ccafe24', 'ccafe16', 'ccalarca9', 'ccalarca15'],
  "r-floresta":['ccafe31', 'ccafe33', 'ccafe24', 'ccafe16', 'pijao2', 'pijao3'],
  "r-pijaomercado":['trucha', 'cpatacon25', 'cpatacon23', 'cpatacon6', 'pijao2', 'pijao3'],
  "r-brisa":['cbandeja1', 'cbandeja8', 'cbandeja9', 'cbandeja2', 'cbandeja15', 'csopas10'],
  "r-genovamercado":['carepa14', 'cempanada3', 'ccafe24', 'cgenova2', 'cgenova3'],
  "r-cordobakumis":['cpostres4', 'cpostres2', 'arepa', 'cbandeja1', 'cbandeja8', 'cbandeja9'],
  "r-corredor":['carepa19', 'carepa14', 'carepa8', 'cchocolate3', 'ctebaida1', 'ctebaida2'],
  "h-salentoreal":['csalento0', 'csalento10', 'csalento11', 'csalento7'],
  "h-coffeetree":['csalento0', 'csalento10', 'csalento11', 'csalento7'],
  "h-piedemonte":['ccocora0', 'cbirds28', 'ccafe16', 'csalento0', 'csalento10'],
  "h-viajero":['csalento0', 'csalento10', 'csalento11', 'csalento7'],
  "h-terrazas":['csalento0', 'csalento10', 'csalento11', 'csalento7'],
  "h-masia":['ccocora0', 'cbirds28', 'ccafe16', 'csalento0', 'csalento10'],
  "h-montanablue":['ccocora0', 'cbirds28', 'ccafe16', 'csalento0', 'csalento10'],
  "h-tukawa":['cfilandia32', 'crest23'],
  "h-santamaria":['cfilandia32', 'crest23'],
  "h-findland":['cfilandia32', 'crest23'],
  "h-bidea":['cfilandia32', 'crest23'],
  "h-colina":['cfilandia32', 'crest23'],
  "h-compadre":['cfilandia32', 'crest23'],
  "h-balsora":['ccafe16', 'cfilandia32', 'crest23'],
  "h-armeniahotel":['carmenia8', 'carmenia0'],
  "h-balso":['ccafe16', 'carmenia8', 'carmenia0'],
  "h-bremen":['ccircasia30', 'ccircasia23', 'ccircasia29'],
  "h-orquideas":['ccircasia30', 'ccircasia23', 'ccircasia29'],
  "h-casanova":['ccafe16', 'ccircasia30', 'ccircasia23', 'ccircasia29'],
  "h-paraiso":['ccafe16', 'ccircasia30', 'ccircasia23', 'ccircasia29'],
  "h-despertar":['ccafe16', 'ccircasia30', 'ccircasia23', 'ccircasia29'],
  "h-machangara":['ccafe16', 'cpanaca5'],
  "h-decameron":['cpanaca5'],
  "h-casaquecanta":['cpanaca5'],
  "h-casanostra":['ccafe16', 'cpanaca5'],
  "h-percal":['ccafe16', 'cparque17', 'cmontenegro0'],
  "h-montecarlos":['ccafe16', 'cparque17', 'cmontenegro0'],
  "h-lapaloma":['ccafe16', 'cparque17', 'cmontenegro0'],
  "h-sanalbertohotel":['cbuenavista1', 'buenavista2'],
  "h-miradorcafe":['cbuenavista1', 'buenavista2'],
  "h-lacima":['ccafe16', 'cbuenavista1', 'buenavista2'],
  "h-elvira":['ccafe16', 'cbuenavista1', 'buenavista2'],
  "h-karlaka":['ccalarca9', 'ccalarca15', 'ccalarca10'],
  "h-plazacalarca":['ccalarca9', 'ccalarca15', 'ccalarca10'],
  "h-mahavan":['ccalarca9', 'ccalarca15', 'ccalarca10'],
  "h-combia":['ccafe16', 'ccalarca9', 'ccalarca15', 'ccalarca10'],
  "h-casavictoria":['pijao2', 'pijao3'],
  "h-tarapaka":['pijao2', 'pijao3'],
  "h-panorama":['pijao2', 'pijao3'],
  "h-laplaya":['ccafe16', 'pijao2', 'pijao3'],
  "h-genovareal":['cgenova2', 'cgenova3'],
  "h-klaret":['cgenova2', 'cgenova3'],
  "h-riversidegenova":['cgenova2', 'cgenova3'],
  "h-losjuanes":['ccordoba1'],
  "h-casonaabuela":['ccordoba1'],
  "h-sonarte":['ccafe16', 'ccordoba1'],
  "h-mocawa":['ctebaida1', 'ctebaida2'],
  "h-miradorpalmas":['ctebaida1', 'ctebaida2'],
  "h-herencia":['ctebaida1', 'ctebaida2'],
  "h-maravelez":['ccafe16', 'ctebaida1', 'ctebaida2']
};
